apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      selectPolicy: Min
  minReplicas: {{ .Values.minPods }}
  maxReplicas: {{ .Values.maxPods }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40