name: Deploy Image to Kubernetes

on:
  workflow_call:
    inputs:
      target_environment:
        description: "The GKE Namespace to Deploy To"
        required: true
        type: string
      image_name:
        description: "The gcr.io repo image to deploy"
        required: true
        type: string
      project_id:
        description: "The name of the GCP project"
        required: true
        type: string
      release_suffix:
        description: "Follows the image_name in helm release to provide uniqueness when deploying multiple configurations of the same image"
        required: false
        default: ""
        type: string
      tag_to_deploy:
        description: "The gcr.io repo image tag to deploy"
        required: true
        default: "release"
        type: string
      replica_count:
        description: "The number of Pod replicas to create"
        required: true
        type: string
        default: "1"
      helm_deploy_set_env_vars:
        description: "If you have non-sensitive environment variables to pass to the deploy do it here"
        required: false
        default: ""
        type: string
      infrastructure_folder: # TODO Convert this to use helm folders properly
        description: "If your deployment should reference a directory other than .infra, use this variable, specify the exact path with the . (ex. .cron_infra)"
        required: false
        default: ".infra"
        type: string
      timeout:
        description: "The time helm will wait for all requested replicas to be healthy"
        required: false
        default: "5m"
        type: string
    secrets:
      GKE_SA_KEY:
        required: true
      CLUSTER_NAME:
        required: true
      CLUSTER_LOCATION:
        required: true
      HELM_DEPLOY_SET_SECRET_ENV_VARS:
        required: false

jobs:
  ###################################
  # Run kubectl/Helm related scripts
  ###################################
  reusable_image_deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP authentication
        uses: google-github-actions/auth@v1
        with: # TODO We should be using Workload identities for better security, get the cluster to support that
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ inputs.project_id }}
          create_credentials_file: true

      - name: GKE authentication
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.CLUSTER_LOCATION }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Helm Install
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Print and Lint Helm chart
        run: |
          helm template ${{ inputs.image_name }} ${{ inputs.infrastructure_folder }} \
            -f ${{ inputs.infrastructure_folder }}/${{ inputs.target_environment }}-values.yaml \
            --set count=${{ inputs.replica_count }} \
            --set image.name=${{ inputs.image_name }} \
            --set image.tag=${{ inputs.tag_to_deploy }} \
            --namespace ${{ inputs.target_environment }} \
            --debug \
            --set secrets=OMITTED \
            ${{ inputs.helm_deploy_set_env_vars }}

          helm lint ${{ inputs.infrastructure_folder }} \
            -f ${{ inputs.infrastructure_folder }}/${{ inputs.target_environment }}-values.yaml \
            --namespace ${{ inputs.target_environment }} \
            --strict \
            --debug

      - name: Deploy Application
        run: |
          helm upgrade ${{ inputs.image_name }} ${{ inputs.infrastructure_folder }} \
            -f ${{ inputs.infrastructure_folder }}/${{ inputs.target_environment }}-values.yaml \
            --set count=${{ inputs.replica_count }} \
            --set image.name=${{ inputs.image_name }} \
            --set image.tag=${{ inputs.tag_to_deploy }} \
            --namespace ${{ inputs.target_environment }} \
            --timeout ${{ inputs.timeout }} \
            --create-namespace \
            --install \
            --debug \
            --wait \
            ${{ secrets.HELM_DEPLOY_SET_SECRET_ENV_VARS }}
            ${{ inputs.helm_deploy_set_env_vars }}
