name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The name to give the image"
        required: true
        type: string
      project_id:
        description: "The name of the GCP project"
        required: true
        type: string
    secrets:
      GKE_SA_KEY:
        required: true

jobs:
  ###################################
  # Run Docker build and push
  ###################################
  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    #   permissions:
    #      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GCP authentication
        id: gcp_auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ inputs.project_id }}
          create_credentials_file: true

      - name: GCR Login
        run: |-
          gcloud --quiet auth configure-docker

      # Action Docs - https://github.com/marketplace/actions/git-semantic-version
      - name: Increment Release Image Version
        id: release_bump_version
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"

      - name: Increment PR Image Version
        id: pr_bump_version
        if: github.event_name == 'pull_request'
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}-${{ github.head_ref }}${increment}"

      - name: Increment Feature Image Version
        id: feature_bump_version
        if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}-${{ github.ref_name }}${increment}"

      - name: Build Tagged Image
        run: |-
          docker build \
            --tag "gcr.io/${{ inputs.project_id }}/${{ inputs.image_name }}:latest" \
            --tag "gcr.io/${{ inputs.project_id }}/${{ inputs.image_name }}:$GITHUB_SHA" \
            --tag "gcr.io/${{ inputs.project_id }}/${{ inputs.image_name }}:${{ github.event_name == 'pull_request' && github.head_ref  || github.ref_name }}" \
            --tag "gcr.io/${{ inputs.project_id }}/${{ inputs.image_name }}:${{ steps.release_bump_version.outputs.version || steps.pr_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}" \
            .

      - name: Push Image to GCR
        run: |-
          docker push "gcr.io/${{ inputs.project_id }}/${{ inputs.image_name }}" --all-tags

      # Action Docs - https://github.com/softprops/action-gh-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ steps.release_bump_version.outputs.version || steps.pr_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
