name: Build and Publish Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The name to give the image"
        required: true
        type: string
    secrets:
      GKE_SA_KEY:
        required: true
      
env:
  PROJECT_ID: gallop-api
  GKE_ZONE: us-central1

jobs:
  ###################################
  # Run Docker build and push
  ###################################
  docker-build-push:
    name: Docker Build & Push
    needs: quality-checks
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for version increment

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GCP authentication
        id: gcp_auth
        uses: google-github-actions/auth@v0.7.1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true

      - name: GCR Login
        run: |-
          gcloud --quiet auth configure-docker

      # Action Docs - https://github.com/marketplace/actions/git-semantic-version
      - name: Increment PR Image Version
        id: bump_version
        if: github.event_name == 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}-${{ github.head_ref }}${increment}'

      - name: Increment Release Image Version
        id: bump_version
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}'

      - name: Increment Feature Image Version
        id: bump_version
        if: github.ref != 'refs/heads/master' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}-${{ github.ref_name }}${increment}'

      - name: Build Tagged Image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:latest" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:$GITHUB_SHA" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:${{ github.event_name == 'pull_request' && github.head_ref  || github.ref_name }}" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:${{ steps.bump_version.outputs.version }}" \
            .

      - name: Push Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/${{ inputs.image_name }}" --all-tags

      # Action Docs - https://github.com/softprops/action-gh-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
