name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The name to give the image"
        required: true
        type: string
      include_prisma:
        description: "True to fetch prisma.schema from similarly named branch in migrations repo for prisma generation"
        required: false
        default: false
        type: boolean
    secrets:
      GKE_SA_KEY:
        required: true
      GHA_PRIVATE_REPO_TOKEN:
        required: false
      
env:
  PROJECT_ID: gallop-api
  GKE_ZONE: us-central1

jobs:
  ###################################
  # Run Docker build and push
  ###################################
  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for version increment

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GCP authentication
        id: gcp_auth
        uses: google-github-actions/auth@v0.8.1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true

      - name: GCR Login
        run: |-
          gcloud --quiet auth configure-docker

      # Action Docs - https://github.com/marketplace/actions/git-semantic-version
      - name: Increment Release Image Version
        id: release_bump_version
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}'

      - name: Increment PR Image Version
        id: pr_bump_version
        if: github.event_name == 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}-${{ github.head_ref }}${increment}'

      - name: Increment Feature Image Version
        id: feature_bump_version
        if: github.ref != 'refs/heads/master' && github.event_name != 'pull_request'
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ""
          format: '${major}.${minor}.${patch}-${{ github.ref_name }}${increment}'

      - name: Download Database Prisma Schema
        id: fetch_schema
        if: inputs.include_prisma
        run: |-
          curl -LJ -H 'Authorization: token ${{ secrets.GHA_PRIVATE_REPO_TOKEN }}' -o ./schema.prisma  https://raw.githubusercontent.com/gallop-data/migrations/${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}/prisma/schema.prisma
        
      - name: Build Tagged Image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:latest" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:$GITHUB_SHA" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:${{ github.event_name == 'pull_request' && github.head_ref  || github.ref_name }}" \
            --tag "gcr.io/$PROJECT_ID/${{ inputs.image_name }}:${{ steps.release_bump_version.outputs.version || steps.pr_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}" \
            .

      - name: Push Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/${{ inputs.image_name }}" --all-tags

      # Action Docs - https://github.com/softprops/action-gh-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ steps.release_bump_version.outputs.version || steps.pr_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
